### ISSUE TITLE
Error 000824 in ArcGIS: The tool is not licensed

### ISSUE THREAD

**Issue by stephanbuettig** [tsamsonov/supplementary-contours#1]
Hi,

I tried to run the supplementary contours tool on various ArcGIS desktop versions (v10.5.-10.7.) with different licenses (basic, advanced). However, each time the error "Error: 000824: The tool is not licensed" occurred.

![Error](https://user-images.githubusercontent.com/25052791/69798663-02713780-11d2-11ea-9b03-34af5896bde7.PNG)

Is this problem known?

Alternatively I'd also like to get a QGIS plugin for this job! ;-)

Greetings

Stephan

**Comment by tsamsonov** [comment]
Hi, @unfassbarstephan, It seems that the tool cannot find Spatial Analyst (SA) extention, which is required. Do you have SA license?

Concerning QGIS tool — it is planned, but, considering my current schedule, not earlier than Q2 2020.

**Comment by stephanbuettig** [comment]
Hi,
thanks for your fast reply!

That's the snag. But I can't get a license for Spatial Analyst (SA) extention, so I'm anxiously waiting for the QGIS plugin.

Greetings

**Comment by tsamsonov** [comment]
Thank you for your feedback! QGIS version is planned next year, as I mentioned. Let's look how fast it goes.
